version: '3.8'

services:
  elasticsearch:
    container_name: observability-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    volumes:
      - ./docker/elastic/data:/usr/share/elasticsearch/data  
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - 9200:9200
    networks:
      - webapi

  kibana:
    container_name: observability-kibana
    image: docker.elastic.co/kibana/kibana:8.6.2
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    networks:
      - webapi

  webapi:
    # image: dmagnovasconcelos/dotnet-website:v1.0
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: observability-webapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - elasticsearch
    ports:
      - "8080:80"
    networks:
      - webapi

  prometheus:
    container_name: observability-prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./docker/prometheus/config:/etc/prometheus/
      - ./docker/prometheus/data:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - webapi
    networks:
      - webapi
      
  grafana:
    container_name: observability-grafana
    image: grafana/grafana:latest
    links:
      - prometheus:prometheus
    volumes:
      - ./docker/grafana/data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - webapi

  jaeger:
    container_name: observability-jaeger
    image: jaegertracing/all-in-one:latest
    hostname: jaeger
    volumes:
      - "./docker/jaeger/data:/etc/jaeger/jaeger-ui.json"
    restart: always
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    networks:
      - webapi
    
networks:
  webapi:
    driver: bridge